In [14]:
import numpy as np

In [8]:
arr = np.array([1, 2, 3, 2, 5, 10, 3])

In [9]:
bol = arr > 2

In [10]:
bol

array([False, False,  True, False,  True,  True,  True])

In [33]:
x = np.random.randn(5)
y = np.random.randn(5)

z = np.maximum(x, y)

print(x)
print(y)
print(z)

[ 0.79747099 -0.78879503  1.05435418 -2.70064851  3.26426964]
[ 1.70981136  0.4292347   0.86416837 -1.78112735  1.49713923]
[ 1.70981136  0.4292347   1.05435418 -1.78112735  3.26426964]


In [35]:
np.sin(z)

array([ 0.99035296,  0.41617505,  0.86958151, -0.97796186, -0.12236951])

In [40]:
narr = np.random.randn(5, 5)

narr

array([[-1.23645834, -0.26894879, -0.75484463,  0.90364388, -0.01171808],
       [ 0.20106157, -0.11744971,  0.15191561, -1.84961753, -0.6813158 ],
       [ 0.15433718, -0.48827983,  0.01042561,  0.87004466, -0.92417235],
       [-1.0819212 ,  1.22455253,  2.67784927,  0.30915181,  0.47643473],
       [ 0.46635301, -1.30685521, -0.64548182,  0.17487475, -0.51303448]])

In [43]:
narr.sum(axis=1)

array([-1.36832595, -2.29540587, -0.37764473,  3.60606715, -1.82414374])

In [45]:
np.diagonal(narr)

array([-1.23645834, -0.11744971,  0.01042561,  0.30915181, -0.51303448])

In [50]:
ones = np.zeros((5, 5))

ones

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])