# Exercícios NumPy

**Importe NumPy como np**

In [2]:
import numpy as np

**Crie uma matriz de 10 zeros**

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Crie uma matriz de 10 ones**

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Crie uma matriz de 10 cincos**

In [5]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

**Crie um array de inteiros de 10 até 50**

In [21]:
np.arange(10, 51, 1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**Crie um array dos numeros pares de 10 até 50**

In [27]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Criei uma matriz 3x3 com valores variando de 0 até 8**

In [33]:
np.random.randn(8)

array([ 0.89792539,  0.53773398,  0.7835399 , -1.25458457, -0.49305625,
       -1.67050517, -0.244919  , -1.71502993])