# Atividade SVM
Luan Rodrigues Petruitis
GU3011356

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
import seaborn as sns
%matplotlib inline

TypeError: an integer is required (got type bytes)

In [ ]:
anagrams = sns.load_dataset('anagrams')
anagrams

subidr    attnr  num1  num2  num3
0        1  divided     2   4.0     7
1        2  divided     3   4.0     5
2        3  divided     3   5.0     6
3        4  divided     5   7.0     5
4        5  divided     4   5.0     8
5        6  divided     5   5.0     6
6        7  divided     5   4.5     6
7        8  divided     5   7.0     8
8        9  divided     2   3.0     7
9       10  divided     6   5.0     6
10      11  focused     6   5.0     6
11      12  focused     8   9.0     8
12      13  focused     6   5.0     9
13      14  focused     8   8.0     7
14      15  focused     8   8.0     7
15      16  focused     6   8.0     7
16      17  focused     7   7.0     6
17      18  focused     7   8.0     6
18      19  focused     5   6.0     6
19      20  focused     6   6.0     5

In [ ]:
anagrams.keys()

Index(['subidr', 'attnr', 'num1', 'num2', 'num3'], dtype='object')

In [ ]:
print(anagrams['attnr'])

0     divided
1     divided
2     divided
3     divided
4     divided
5     divided
6     divided
7     divided
8     divided
9     divided
10    focused
11    focused
12    focused
13    focused
14    focused
15    focused
16    focused
17    focused
18    focused
19    focused
Name: attnr, dtype: object


In [ ]:
df_num2 = pd.DataFrame(anagrams['num1'],columns=anagrams['num2'])
df_num2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 20 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   4.0     0 non-null      object
 1   4.0     0 non-null      object
 2   5.0     0 non-null      object
 3   7.0     0 non-null      object
 4   5.0     0 non-null      object
 5   5.0     0 non-null      object
 6   4.5     0 non-null      object
 7   7.0     0 non-null      object
 8   3.0     0 non-null      object
 9   5.0     0 non-null      object
 10  5.0     0 non-null      object
 11  9.0     0 non-null      object
 12  5.0     0 non-null      object
 13  8.0     0 non-null      object
 14  8.0     0 non-null      object
 15  8.0     0 non-null      object
 16  7.0     0 non-null      object
 17  8.0     0 non-null      object
 18  6.0     0 non-null      object
 19  6.0     0 non-null      object
dtypes: object(20)
memory usage: 0.0+ bytes


In [ ]:
target = anagrams["attnr"]
target

0     divided
1     divided
2     divided
3     divided
4     divided
5     divided
6     divided
7     divided
8     divided
9     divided
10    focused
11    focused
12    focused
13    focused
14    focused
15    focused
16    focused
17    focused
18    focused
19    focused
Name: attnr, dtype: object

In [ ]:
df_target = pd.DataFrame(target, columns=anagrams['subidr'])
df_target.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 20 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   1       0 non-null      object
 1   2       0 non-null      object
 2   3       0 non-null      object
 3   4       0 non-null      object
 4   5       0 non-null      object
 5   6       0 non-null      object
 6   7       0 non-null      object
 7   8       0 non-null      object
 8   9       0 non-null      object
 9   10      0 non-null      object
 10  11      0 non-null      object
 11  12      0 non-null      object
 12  13      0 non-null      object
 13  14      0 non-null      object
 14  15      0 non-null      object
 15  16      0 non-null      object
 16  17      0 non-null      object
 17  18      0 non-null      object
 18  19      0 non-null      object
 19  20      0 non-null      object
dtypes: object(20)
memory usage: 0.0+ bytes


In [ ]:
from sklearn.model_selection import train_test_split

x = df_num2.columns.to_numpy()
y = df_target.columns.to_numpy()
print(x)
print(y)

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.02, random_state=101)

print(X_train)
print(X_test)
print(y_train)
print(y_test)

[4.  4.  5.  7.  5.  5.  4.5 7.  3.  5.  5.  9.  5.  8.  8.  8.  7.  8.
 6.  6. ]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[7.  5.  4.  5.  7.  8.  6.  4.  5.  5.  5.  3.  8.  5.  8.  6.  4.5 8.
 9. ]
[7.]
[ 8  3  2 11 17 15 19  1  6 13  5  9 14 10 16 20  7 18 12]
[4]


In [ ]:
from sklearn.svm import SVC
model = SVC()

X_train = X_train.reshape(-1, 1)
y_train = y_train.reshape(-1, 1)

model.fit(X_train,y_train)

c:\Users\danie\projects\examples\python\data-science-python\venv\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [ ]:
X_test = X_test.reshape(-1, 1)
predictions = model.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
print(confusion_matrix(y_test,predictions))

[[0 1]
 [0 0]]


In [ ]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           4       0.00      0.00      0.00       1.0
          17       0.00      0.00      0.00       0.0

    accuracy                           0.00       1.0
   macro avg       0.00      0.00      0.00       1.0
weighted avg       0.00      0.00      0.00       1.0



c:\Users\danie\projects\examples\python\data-science-python\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\danie\projects\examples\python\data-science-python\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\danie\projects\examples\python\data-science-python\venv\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior

In [ ]:
param_grid = {
    'C': [0.1, 1, 10, 100, 1000], 
    'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
    'kernel': ['rbf']
}

from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(SVC(), param_grid, refit=True, verbose=3)
print(X_train.shape)
print(y_train.shape)
grid.fit(X_train,y_train)

(19, 1)
(19, 1)
Fitting 5 folds for each of 25 candidates, totalling 125 fits


ValueError: n_splits=5 cannot be greater than the number of members in each class.